### ISSUE TITLE
Add GN Group software support

### ISSUE THREAD

**Issue by JohnnySaliba** [Bluebotlabz/Universal-Hearing-Aid-Software-Downloader#1]
Resound downloads are available at this link:

http://www.supportgn.com/resound/subsites/releases_updates_patches.php

Beltone:

http://www.supportgn.com/beltone/subsites/releases_updates_patches.php

Interton:

http://www.supportgn.com/interton/subsites/releases_updates_patches.php

There's some old drivers and documents available for all three if you click "Home" in the top left corner, and the "Fitting Software Inventory Tool" available at www.supportgn.com

**Comment by Bluebotlabz** [comment]
Thank you for this!

I'll try to implement it in the next update

**Comment by JohnnySaliba** [comment]
It did take me some time to find them so I suspect it might take others too. 

I'd encourage you to add it because fitting software being available was a huge part of which HA brand I went with, and I made sure I had a working download before I decided.

**Comment by Bluebotlabz** [comment]
Added to [v1.7.0](https://github.com/Bluebotlabz/Universal-Hearing-Aid-Software-Downloader/releases/tag/v1.7.0)
