### ISSUE TITLE
No success with the Downloader

### ISSUE THREAD

**Issue by Jorindel53** [Bluebotlabz/Universal-Hearing-Aid-Software-Downloader#5]
Hello, 
it doesn't work, please have a look at the screen shots.
Hoping for help!
Jorinde

![process-1](https://user-images.githubusercontent.com/60181429/203572478-d2036ca5-5b7a-4780-8a7d-fdf7491e0699.jpg)
![process-2](https://user-images.githubusercontent.com/60181429/203572571-308f0b47-7424-4c57-aaf9-e84ef3c3aea3.jpg)

**Comment by Bluebotlabz** [comment]
This should be fixed in the latest release

**Comment by Jorindel53** [comment]
Works fine, thank you!
